<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\ConfigurableProduct\Pricing\Render\FinalPriceBox $block */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;

// Calculate discount percentage
$regularPrice = $priceModel->getAmount()->getValue();
$finalPrice = $finalPriceModel->getAmount()->getValue();
$discountPercentage = 0;
if ($regularPrice > 0 && $regularPrice > $finalPrice) {
    $discountPercentage = (($regularPrice - $finalPrice) / $regularPrice) * 100;
}
?>

<?php if (!$block->isProductList() && $block->hasSpecialPrice()) : ?>
    <span class="old-price sly-old-price no-display">
        <?= /* @noEscape */ $block->renderAmount($priceModel->getAmount(), [
            'display_label'     => __(''),
            'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
            'price_type'        => 'oldPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
    </span>
<?php endif; ?>

<span class="normal-price">
    <?= /* @noEscape */ $block->renderAmount($finalPriceModel->getAmount(), [
        'display_label' => __(''),
        'price_id' => $block->getPriceId('product-price-' . $idSuffix),
        'price_type' => 'finalPrice',
        'include_container' => true,
        'schema' => $schema,
    ]); ?>
    
    

<?php if ($block->showMinimalPrice()) : ?>
    <?php if ($block->getUseLinkForAsLowAs()) : ?>
        <a href="<?= $block->escapeUrl($block->getSaleableItem()->getProductUrl()) ?>" class="minimal-price-link">
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        </a>
    <?php else : ?>
        <span class="minimal-price-link">
            <?= /* @noEscape */ $block->renderAmountMinimal() ?>
        </span>
    <?php endif; ?>
<?php endif; ?>

<script type="text/javascript">
    require(['jquery'], function ($) {
    $(document).ready(function () {
        // Function to update the discount percentage
        function updateDiscountPercentage() {
            var regularPrice = parseFloat($('.old-price .price').text().replace(/[^\d.-]/g, ''));
            var finalPrice = parseFloat($('.normal-price .price').text().replace(/[^\d.-]/g, ''));

            if (!isNaN(regularPrice) && !isNaN(finalPrice) && regularPrice > finalPrice) {
                var discountPercentage = ((regularPrice - finalPrice) / regularPrice) * 100;
                $('.discount-percentage').text(discountPercentage.toFixed(2) + '% OFF');
                
              
            } else {
                $('.discount-percentage').empty();
                
                
            }
        }

        // Trigger the update on page load
        updateDiscountPercentage();

        // Event delegation for text swatch click
        // $(document).on('click', '.swatch-option.text', function (){
       $("body").delegate(".swatch-option.text", "click", function() {
            // Delayed update to ensure the swatch change is complete
            setTimeout(updateDiscountPercentage, 500);
        });

        // Event delegation for select dropdown change
        $(document).on('change', '.super-attribute-select', function () {
            // Delayed update to ensure the select dropdown change is complete
            setTimeout(updateDiscountPercentage, 500);
        });
    });
});

</script>

