<?php
$categoryId = 6; // Change this to the ID of your desired category

/** @var \Magento\Catalog\Model\ResourceModel\Category\Collection $subcategories */
$subcategories = $block->getSubcategories($categoryId);

?>
<style>
    /* Dropdown Button */
/* .dropbtn {
  background-color: #04AA6D;
  color: white;
  padding: 16px;
  font-size: 16px;
  border: none;
} */

/* The container <div> - needed to position the dropdown content */
.category-dropdown {
  position: relative;
  display: inline-block;
}

/* Dropdown Content (Hidden by Default) */
.dropdown-content {

    background: #fff;
    border: 1px solid #ccc;
    box-shadow: 0 5px 5px rgba(0,0,0,0.19);
    font-weight: 400;
    min-width: 230px;
    padding: 0;
    display: none;
    left: 0;
    margin: 0 !important;
    position: absolute;
    z-index: 1;

}

/* Links inside the dropdown */
.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

/* Change color of dropdown links on hover */
.dropdown-content a:hover {background-color: #ddd;}

/* Show the dropdown menu on hover */
.category-dropdown:hover .dropdown-content {display: block;}

/* Change the background color of the dropdown button when the dropdown content is shown */
    </style>
<div class="category-dropdown">
<p class="header-category-title">Categories</p>
<?php if ($subcategories->count() > 0) : ?>
  <div class="dropdown-content">
  <?php foreach ($subcategories as $subcategory) : ?>
    <a href="<?= $subcategory->getUrl() ?>">
                <?= $block->escapeHtml($subcategory->getName()) ?>
                </a>
                <?php endforeach; ?>
  </div>
</div>
<?php endif; ?>
<!-- <?php if ($subcategories->count() > 0) : ?>
    <ul class="category-block">
        <p class="category-title">Categories</p>
        <div class="allcategories">
        <?php foreach ($subcategories as $subcategory) : ?>
            <li>
                <a href="<?= $subcategory->getUrl() ?>">
                <?= $block->escapeHtml($subcategory->getName()) ?>
                </a>
            </li>
        <?php endforeach; ?>
        </div>
    </ul>

<?php endif; ?> --> 