<div class="shopbycategories">
    <?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $categoryFactory = $objectManager->get('\Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
    
    $allCategories = $categoryFactory->create();
    $allCategories->addAttributeToSelect(['name', 'image']); // Add more attributes if needed
    $allCategories->addAttributeToFilter('is_active', 1); // Filter only enabled categories
    ?>

    <?php if ($allCategories->count() > 0) : ?>
        <h2 class="category-title">Categories</h2>
        <ul class="category-block">
            <?php foreach ($allCategories as $category) : ?>
                <li class="item">
                    <a href="<?= $category->getUrl() ?>">
                        <?php if ($category->getImage()) : ?>
                            <?php
                            $imagePath = $category->getImage();
                            ?>
                            <img class="categpory-image" src="<?= $imagePath ?>" alt="<?= $block->escapeHtml($category->getName()) ?>">
                        <?php endif; ?>
                    </a>
                    <p class="category-name"><?= $block->escapeHtml($category->getName()) ?></p>
                </li>
            <?php endforeach; ?>
        </ul>
    <?php else : ?>
        <p>No categories found.</p>
    <?php endif; ?>
</div>
