<?php
$categoryId = 6; // Change this to the ID of your desired category

/** @var \Magento\Catalog\Model\ResourceModel\Category\Collection $subcategories */
$subcategories = $block->getSubcategories($categoryId);
$subcategories->addAttributeToSelect(['name', 'image']); // Add image attribute

?>
<?php if ($subcategories->count() > 0) : ?>
    <h2 class="category-title">Categories</h2>
    <div class="owl-carousel">
        <?php foreach ($subcategories as $subcategory) : ?>
            <div class="item">
                <a href="<?= $subcategory->getUrl() ?>">
                    <?php if ($subcategory->getImage()) : ?>
                        <?php
                        $imagePath =  $subcategory->getImage();
                        ?>
                        <img class="categpory-image" src="<?= $imagePath ?>" alt="<?= $block->escapeHtml($subcategory->getName()) ?>">
                    <?php endif; ?>
                </a>
                <p class="category-name"><?= $block->escapeHtml($subcategory->getName()) ?></p>
            </div>
        <?php endforeach; ?>
    </div>
<?php else : ?>
    <p>No subcategories found.</p>
<?php endif; ?>
<script>
    require(['jquery', 'owlcarousel'], function($){
    $(document).ready(function(){
        $(".owl-carousel").owlCarousel({
            items: 1,
            margin: 20,
            responsive: {
                640: {
                    items: 2,
                    margin: 7,
                },
                480: {
                    items: 1,
                    margin: 7,
                },
            },
        });
    });
});
</script>