<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get(\Magento\Store\Model\StoreManagerInterface::class);
$mediaUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$price = $mediaUrl . "trustworthy/best-prices.png";
$support = $mediaUrl . "trustworthy/customer-support.png";
$years = $mediaUrl . "trustworthy/19-years.png";
?>

<div class="home_tags_sec">
        <div class="home_tags_blk">
                <div class="main_col">
                        <div class="tag blk 1">
                                <div class="img_tag">
                                        <img src="<?php echo $price ?>" alt="best prices logo">
                                </div>
                                <div class="content_tag">
                                        <p class="main_tle_tag">BEST PRICES</p>
                                        <p class="sub_tlt_tag">unbeatable deals and offers</p>
                                </div>
                        </div>
                        <div class="tag blk 2">
                                <div class="img_tag">
                                        <img src="<?php echo $support ?>" alt="">
                                </div>
                                <div class="content_tag">
                                        <p class="main_tle_tag">EXCELLENT CUSTOMER SERVICE</p>
                                        <p class="sub_tlt_tag">reliable and friendly support</p>
                                </div>
                        </div>
                        <div class="tag blk 3">
                                <div class="img_tag">
                                        <img src="<?php echo $years ?>" alt="">
                                </div>
                                <div class="content_tag">
                                        <p class="main_tle_tag">TRUSTED BY CUSTOMERS</p>
                                        <p class="sub_tlt_tag">for over 19+ years</p>
                                </div>
                        </div>
                </div>
        </div>
</div>